### PR TITLE
Fix: Remove obsolete link command that causes file system loop.

### LINKED ISSUE #225: AiiDAlab fails to start with error `File system loop detected; ‘/home/aiida/aiida’ is part of the same file system loop as ‘/home/aiida’.`
After I clean the `.trash/` and rerun the `manage.py` I got:

```
...
aiidalab_1  | + verdi daemon stop
aiidalab_1  | Profile: default
aiidalab_1  | Warning: Deleted apparently stale daemon PID file as its associated process<1276> does not exist anymore
aiidalab_1  | Waiting for the daemon to shut down... The daemon was not running.
aiidalab_1  | + verdi database migrate --force
aiidalab_1  | + verdi daemon start
aiidalab_1  | Starting the daemon... RUNNING
aiidalab_1  | *** Running /etc/my_init.d/80_prepare-aiidalab.sh...
aiidalab_1  | + export SHELL=/bin/bash
aiidalab_1  | + SHELL=/bin/bash
aiidalab_1  | + '[' '!' -e /home/aiida/.ipython/profile_default/startup/aiida_magic_register.py ']'
aiidalab_1  | + '[' '!' -e /home/aiida/apps ']'
aiidalab_1  | + '[' '!' -e /home/aiida/apps/home ']'
aiidalab_1  | + [[ -d /home/aiida/apps/home ]]
aiidalab_1  | + [[ ! -L /home/aiida/apps/home ]]
aiidalab_1  | + [[ '' == 1 ]]
aiidalab_1  | + reentry scan
aiidalab_1  | + '[' -e /home/aiida/.trash ']'
aiidalab_1  | + find -L /home/aiida -maxdepth 3 -name apps_meta.sqlite -delete
aiidalab_1  | find: File system loop detected; ‘/home/aiida/aiida’ is part of the same file system loop as ‘/home/aiida’.
aiidalab_1  | *** /etc/my_init.d/80_prepare-aiidalab.sh failed with status 1
aiidalab_1  | 
aiidalab_1  | *** Killing all processes...
aiidalab_1  | Nov 15 12:48:07 53e6cb9c8379 syslog-ng[115]: syslog-ng shutting down; version='3.13.2'
aiidalab-docker-stack_aiidalab_1 exited with code 1
```

_Originally posted by @unkcpz in https://github.com/aiidalab/aiidalab-docker-stack/issues/223#issuecomment-968879111_

### PR DESCRIPTION
**Pull request by csadorf**
Fixes #225.

### CODE REVIEW

File: my_init.d/prepare-aiidalab.sh [hunk 1]
```diff
@@ -1,9 +1,6 @@
 #!/bin/bash
 set -em
 
-# For backwards compatibility
-ln -sf /home/${SYSTEM_USER} /project
```
Comment (ltalirz) [inline my_init.d/prepare-aiidalab.sh:5]: just to understand: is this causing the issue (and if so, why?)

Comment (csadorf) [reply my_init.d/prepare-aiidalab.sh:5]: Yes, this is causing the issue, because the link will be created a second time within the target directory (the link source) when this command is executed twice.

You can test this yourself, by executing the following commands in a terminal:

```bash
mkdir ~/aiidalab-docker-stack-issue-225
cd ~/aiidalab-docker-stack-issue-225
mkdir -p home/aiida
ln -sf home/aiida project  # fine
ln -sf home/aiida project # creates loop
```

```console
$ ls -l home/aiida
lrwxrwxrwx 1 sadorf sadorf 10 Jan  5 18:30 aiida -> home/aiida
```
It is not clear to me why this issue has only occurred "recently" since this command has been around for a long time, but I am confident that it is the cause of the problem.

Comment (yakutovicha) [reply my_init.d/prepare-aiidalab.sh:5]: > It is not clear to me why this issue has only occurred "recently" since this command has been around for a long time, but I am confident that it is the cause of the problem.

Because those "loops" were revealed by the `find` methods added to the docker startup files quite recently.

**Review by yakutovicha — APPROVED** [review]

**Comment by ltalirz** [comment]
Thanks @csadorf  for getting to the bottom of this!
